### ISSUE TITLE
Error when running mgsa

### ISSUE THREAD

**Issue by f-heeger** [sba1/mgsa-bioc#8]
Hi,

I have been using your package for my analysis and am very happy with the results. Unfortunately I get the following error for one of my data sets:

> Error in (function (cl, name, valueClass)  : 
>  assignment of an object of class “NULL” is not valid for @‘nsamples’ in an object of class “MgsaMcmcResults”; is(value, "numeric") is not TRUE

My R code looks like this (minimal example):

> library(mgsa)
>tab=read.table("proteins.interpro.kegg.txt", sep="\t", stringsAsFactors=F, as.is=T)
>setNames = tab[,2]
>sets = strsplit(tab[,4], ',')
>names(sets) = setNames
>
>observations = c( "H314_10037", "H314_04997", "H314_08355", "H314_08624", "H314_07729"
, "H314_03045", "H314_05000", "H314_05272", "H314_09268", "H314_09687"
, "H314_09442")
>
>result=mgsa(observations, sets)

I attached the input file with the gene sets: [proteins.interpro.kegg.txt](https://github.com/sba1/mgsa-bioc/files/185963/proteins.interpro.kegg.txt)

It is running fine with other observations so I don't think it is related to how I load the gene sets.

Any help or comment would be greatly appreciated.

**Comment by sba1** [comment]
I can reproduce the problem. I'll investigate. Thanks for the report.

**Comment by sba1** [comment]
I think that in your example none of the given observations maps to any item within the given sets. Can you verify this? Next version will at least issue a warning in such cases.

**Comment by f-heeger** [comment]
Yes that is right. Should have spotted that. Thanks a lot for looking into it.

**Comment by sba1** [comment]
Thanks for verifying.
